# targets:
#   $default:
#     builders:
#       # A SharedPartBuilder which uses the combining builder
#       source_gen:combining_builder:
#         options:
#           build_extensions:
#             '^lib/features/**/domain/repositories/{{}}.dart': 'lib/features/**/data/repositories/{{}}.g.dart'