name: tdd_clean_atchitecture
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  connectivity_plus: ^4.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.1
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1

  design:
    path: packages/design
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  dio: ^5.3.3
  auto_route: ^7.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8
  source_gen: ^1.4.0
  auto_route_generator: ^7.3.1

flutter:

  uses-material-design: true
